In [25]:
import numpy as np
import itertools
import pandas as pd

### Calculate angular deviation to find the tolerance of the plane fitting to GB measurements

Function to calculate the angle between two vectors:

In [26]:
def angle(n, b): # θ=arctan2(∥n×b∥,|n⋅b|)
    dot = np.dot(n, b)
    normcross = np.linalg.norm(np.cross(n, b))
    dot = abs(dot)  # make angle insensitive to sign flips
    # Use atan2 for better numerical stability than arccos
    return np.degrees(np.arctan2(normcross, dot))

The plane fitting was repeated 5 times for hydride 6:

In [27]:
vectors_hyd6 = {"v1" : np.array([-0.365,0.037,0.930]),
           "v2" : np.array([-0.222, 0.043, 0.974]),
           "v3" : np.array([-0.25, -0.017, 0.967]),
           "v4" : np.array([-0.309, -0.0075, 0.951]),
           "v5" : np.array([-0.318, 0.0279, 0.947]),
}

In [28]:
results = []
for (name1, vec1), (name2, vec2) in itertools.combinations(vectors_hyd6.items(), 2):
    angles = angle(vec1, vec2)
    results.append((name1, name2, np.round(angles,2)))

df = pd.DataFrame(results, columns=["Vector 1", "Vector 2", "Angle (degrees)"])

df

  Vector 1 Vector 2  Angle (degrees)
0       v1       v2             8.59
1       v1       v3             7.59
2       v1       v4             4.27
3       v1       v5             2.91
4       v2       v3             3.82
5       v2       v4             5.92
6       v2       v5             5.78
7       v3       v4             3.55
8       v3       v5             4.81
9       v4       v5             2.11

The plane fitting was repeated 5 times for hydride 8:

In [29]:
vectors_hyd8 = {"v1" : np.array([0.706, 0.113, 0.699]),
           "v2" : np.array([0.691, 0.031, 0.723]),
           "v3" : np.array([0.681, 0.123, 0.721]),
           "v4" : np.array([0.689, 0.046, 0.723]),
           "v5" : np.array([0.684, 0.092, 0.724]),
}

In [30]:
results = []
for (name1, vec1), (name2, vec2) in itertools.combinations(vectors_hyd8.items(), 2):
    angles = angle(vec1, vec2)
    results.append((name1, name2, np.round(angles,2)))

df = pd.DataFrame(results, columns=["Vector 1", "Vector 2", "Angle (degrees)"])

df

  Vector 1 Vector 2  Angle (degrees)
0       v1       v2             4.97
1       v1       v3             1.99
2       v1       v4             4.19
3       v1       v5             2.26
4       v2       v3             5.31
5       v2       v4             0.87
6       v2       v5             3.52
7       v3       v4             4.44
8       v3       v5             1.79
9       v4       v5             2.65

The plane fitting was repeated 5 times for hydride 14:

In [31]:
vectors_hyd14 = {"v1" : np.array([-0.172, 0.949, 0.264]),
           "v2" : np.array([-0.261, 0.900, 0.351]),
           "v3" : np.array([-0.221, 0.914, 0.339]),
           "v4" : np.array([-0.284, 0.913, 0.291]),
           "v5" : np.array([0.311, -0.909, -0.277]),
}

In [32]:
results = []
for (name1, vec1), (name2, vec2) in itertools.combinations(vectors_hyd14.items(), 2):
    angles = angle(vec1, vec2)
    results.append((name1, name2, np.round(angles,2)))

df = pd.DataFrame(results, columns=["Vector 1", "Vector 2", "Angle (degrees)"])

df

  Vector 1 Vector 2  Angle (degrees)
0       v1       v2             7.67
1       v1       v3             5.51
2       v1       v4             6.92
3       v1       v5             8.33
4       v2       v3             2.52
5       v2       v4             3.76
6       v2       v5             5.14
7       v3       v4             4.54
8       v3       v5             6.27
9       v4       v5             1.76

The plane fitting was repeated 5 times for hydride 17:

In [33]:
vectors_hyd17 = {"v1" : np.array([-0.002, 0.981, 0.194]),
           "v2" : np.array([-0.083, -0.997, 0.0059]),
           "v3" : np.array([0.006, -0.996, -0.084]),
           "v4" : np.array([-0.055, -0.997, -0.053]),
           "v5" : np.array([-0.019, 0.994, 0.111]),
}

In [34]:
results = []
for (name1, vec1), (name2, vec2) in itertools.combinations(vectors_hyd17.items(), 2):
    angles = angle(vec1, vec2)
    results.append((name1, name2, np.round(angles,2)))

df = pd.DataFrame(results, columns=["Vector 1", "Vector 2", "Angle (degrees)"])

df

  Vector 1 Vector 2  Angle (degrees)
0       v1       v2            12.50
1       v1       v3             6.37
2       v1       v4             8.77
3       v1       v5             4.91
4       v2       v3             7.25
5       v2       v4             3.74
6       v2       v5             8.90
7       v3       v4             3.92
8       v3       v5             1.72
9       v4       v5             5.39